src/Entity/Enchere.php
<?php

namespace App\Entity;

use App\Repository\EnchereRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: EnchereRepository::class)]

class Enchere
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $derniere_prix = null;

    #[ORM\ManyToOne(inversedBy: 'encheres')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $id_gagnant = null;

    #[ORM\ManyToOne(inversedBy: 'encheres')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Agriculteur $id_agriculteur = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?ProduitEnchere $id_Produit_enchere = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDernierePrix(): ?float
    {
        return $this->derniere_prix;
    }

    public function setDernierePrix(float $derniere_prix): static
    {
        $this->derniere_prix = $derniere_prix;

        return $this;
    }

    public function getIdGagnant(): ?Users
    {
        return $this->id_gagnant;
    }

    public function setIdGagnant(?Users $id_gagnant): static
    {
        $this->id_gagnant = $id_gagnant;

        return $this;
    }

    public function getIdAgriculteur(): ?Agriculteur
    {
        return $this->id_agriculteur;
    }

    public function setIdAgriculteur(?Agriculteur $id_agriculteur): static
    {
        $this->id_agriculteur = $id_agriculteur;

        return $this;
    }

    public function getIdProduitEnchere(): ?ProduitEnchere
    {
        return $this->id_Produit_enchere;
    }

    public function setIdProduitEnchere(ProduitEnchere $id_Produit_enchere): static
    {
        $this->id_Produit_enchere = $id_Produit_enchere;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }
}

src/Form/EnchereType.php
<?php

namespace App\Form;

use App\Entity\Agriculteur;
use App\Entity\Enchere;
use App\Entity\ProduitEnchere;
use App\Entity\Users;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EnchereType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('derniere_prix')
            ->add('date', null, [
                'widget' => 'single_text'
            ])
          
            ->add('id_agriculteur', EntityType::class, [
                'class' => Agriculteur::class,
'choice_label' => 'id',
            ])
            ->add('id_Produit_enchere', EntityType::class, [
                'class' => ProduitEnchere::class,
'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Enchere::class,
        ]);
    }
}

src/Controller/EnchereController.php
<?php

namespace App\Controller;

use App\Entity\Enchere;
use App\Form\EnchereType;
use App\Repository\EnchereRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/enchere')]
final class EnchereController extends AbstractController{
    #[Route(name: 'app_enchere_index', methods: ['GET'])]
    public function index(EnchereRepository $enchereRepository): Response
    {
        return $this->render('enchere/index.html.twig', [
            'encheres' => $enchereRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_enchere_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $enchere = new Enchere();
        $form = $this->createForm(EnchereType::class, $enchere);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($enchere);
            $entityManager->flush();

            return $this->redirectToRoute('app_enchere_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('enchere/new.html.twig', [
            'enchere' => $enchere,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_enchere_show', methods: ['GET'])]
    public function show(Enchere $enchere): Response
    {
        return $this->render('enchere/show.html.twig', [
            'enchere' => $enchere,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_enchere_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Enchere $enchere, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EnchereType::class, $enchere);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_enchere_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('enchere/edit.html.twig', [
            'enchere' => $enchere,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_enchere_delete', methods: ['POST'])]
    public function delete(Request $request, Enchere $enchere, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$enchere->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($enchere);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_enchere_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/enchere/_delete_form.html.twig
<form method="post" action="{{ path('app_enchere_delete', {'id': enchere.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ enchere.id) }}">
    <button class="btn">Delete</button>
</form>

templates/enchere/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/enchere/edit.html.twig
{% extends 'base_front.html.twig' %}

{% block title %}Hello FrontOffice/ProductSingleController!{% endblock %}

{% block body %}
    <h1>Edit Enchere</h1>

    {{ include('enchere/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_enchere_index') }}">back to list</a>

    {{ include('enchere/_delete_form.html.twig') }}
{% endblock %}

templates/enchere/index.html.twig
{% extends 'base_front.html.twig' %}

{% block title %}Hello FrontOffice/ProductSingleController!{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1>Enchere Index</h1>

        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Id</th>
                    <th>Dernière Prix</th>
                    <th>Date</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for enchere in encheres %}
                <tr>
                    <td>{{ enchere.id }}</td>
                    <td>{{ enchere.dernierePrix }}</td>
                    <td>{{ enchere.date ? enchere.date|date('Y-m-d H:i:s') : '' }}</td>
                    <td>
                        <a href="{{ path('app_enchere_show', {'id': enchere.id}) }}" class="btn btn-info btn-sm">Show</a>
                        <a href="{{ path('app_enchere_edit', {'id': enchere.id}) }}" class="btn btn-warning btn-sm">Edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4" class="text-center">No records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('app_enchere_new') }}" class="btn btn-success">Create New</a>
    </div>
{% endblock %}

templates/enchere/new.html.twig
{% extends 'base_front.html.twig' %}

{% block title %}Create New Enchere{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1 class="mb-4">Create New Enchere</h1>

        <!-- Include the form, make sure '_form.html.twig' has Bootstrap styling -->
        {{ include('enchere/_form.html.twig') }}

        <div class="mt-4">
            <a href="{{ path('app_enchere_index') }}" class="btn btn-secondary">Back to List</a>
        </div>
    </div>
{% endblock %}

templates/enchere/show.html.twig
{% extends 'base_front.html.twig' %}

{% block title %}Hello FrontOffice/ProductSingleController!{% endblock %}

{% block body %}
    <h1>Enchere</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ enchere.id }}</td>
            </tr>
            <tr>
                <th>Derniere_prix</th>
                <td>{{ enchere.dernierePrix }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ enchere.date ? enchere.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_enchere_index') }}">back to list</a>

    <a href="{{ path('app_enchere_edit', {'id': enchere.id}) }}">edit</a>

    {{ include('enchere/_delete_form.html.twig') }}
{% endblock %}